service: nequiprueba-lmb-cliente-create

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:    
    PATH_RESOURCES: /v1/clientes/create

functions:
  createCliente:
    handler: handler.create
    events:
      - http:
          path: ${self:provider.environment.PATH_RESOURCES}
          method: post
          cors: true
    memorySize: 128